name: id_card_picker
description: Pick Id Card image
version: 0.1.0+1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  image: ^4.5.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
